export const EntityType = {
  Document: 'document',
  Article: 'article',
  ArticleContent: 'article_content',
  Solicitude: 'solicitude',
  Visit: 'visit',
  Customer: 'customer',
  customer_base: 'customer_base',
  customer_product: 'customer_product',
  customer_quality: 'customer_quality',
  customer_steelRequirement: 'customer_steelRequirement',
  customer_steelAppraise: 'customer_steelAppraise',
  customer_steelProcess: 'customer_steelProcess',
  customer_serving: 'customer_serving',
  customer_contact: 'customer_contact',
  Complain: 'complain',
  ComplainResponseUnit: 'complain_responseUnit',
  ComplainBase: 'complain_base',
  ComplainInitial: 'complain_initial',
  ComplainDuty: 'complain_duty',
  ComplainReform: 'complain_reform',
  ComplainReply: 'complain_reply',
  ComplainVerify: 'complain_verify',
  ServicePlan: 'servicePlan'
}
